use_modular_headers!
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.0'
target "Conventions" do
    pod 'AppAuth'
    pod 'GoogleMaps'
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'UICollectionViewRightAlignedLayout'
    pod 'Firebase/Crashlytics'
    pod 'Firebase/Analytics'
end
